[package]
name = "marsh-github/sync"
description = "Alternative _G table, syncs across all scripts (local and server if you put in ReplicatedStorage).\n\nI've also added more functionality that the _G table otherwise doesn't have."
version = "1.0.1"
license = "Apache-2.0"
authors = ["NotMarshh (Roblox)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["rokit.toml"]

[dependencies]
